---
# This playbook installes NGINX, PHP-FPM , and deploy the required build

- name: MariaDB installation role
  hosts: all_mongodb
  sudo: yes
  roles:
     - common
    # - java
    # - tomcat7
     - mongodb
