---
# This playbook installes NGINX, PHP-FPM , and deploy the required build

- name: Mysql installation role
  hosts: all_mysql
  sudo: yes
  roles:
    # - common
    # - java
    # - tomcat7
     - mysql
