---
  - name: restart haproxy
    service: name=haproxy state=restarted

  - name: reload haproxy
    service: name=haproxy state=reloaded

  - name: restart network
    service: name=network state=restarted
    when: mtu.changed
